# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5f2ee770deb96392372da5c714d2c13e9931e555ff522efb2d43a78eaa85a5e94993bd31445df90a3491fc3489e1954874cd379cac9dfe9d64eb89e4d1bfc6a9

test:
  secret_key_base: 86bb2992d59bd65c98939779e15656cd3f3e1d2283c08ef6129823fd414b54bf32c31659525f9945518c09f59312b28f6ca7d200bdaafd0bcc86c9304d225f13

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
